### ISSUE TITLE
Far Plane View is rendered on the client in dimensions other than the overworld

### ISSUE THREAD

**Issue by CursedFlames** [Foghrye4/CWGFarPlaneView#2]
From looking at the code, it seems that the server checks whether the dimension is 0, and does not send terrain data otherwise, however no check is performed on the client, so it still renders the overworld view in other dimensions - tested in the nether with version 0.1.4, others have reported that this occurs with the end too.  
 (This theory as to why it happens may be incorrect as I haven't managed to get this mod working fully in my dev env)

**Comment by Foghrye4** [comment]
Thank you, fixed.
