### ISSUE TITLE
CWG Far Plane crashes with absolute newest CC+CWG

### ISSUE THREAD

**Issue by Deliphin** [Foghrye4/CWGFarPlaneView#3]
Between test, deleting `.minecraft/mods/1.12.2/`
Crash occurs when trying to load a world. Reaches main menu with no issue.

```
CWGFarPlaneView-0.1.7
CubicChunks-1.12.2-0.0.1007.0-SNAPSHOT-all
CubicWorldGen-1.12.2-0.0.68.0-SNAPSHOT-all
```
Old **curse** CWG FPV, newest **discord** CC+CWG.
Result: **Stable**

```
CWGFarPlaneView-0.2.2
CubicChunks-1.12.2-0.0.1007.0-SNAPSHOT-all
CubicWorldGen-1.12.2-0.0.68.0-SNAPSHOT-all
```
Newest **curse** CWG FPV, newest **discord** CC+CWG.
Result: **Crash**
Crashlog: https://pastebin.com/f4LKqwh6

```
CWGFarPlaneView-0.2.2
CubicChunks-1.12.2-0.0.970.0-SNAPSHOT-all
CubicWorldGen-1.12.2-0.0.39.1-SNAPSHOT-all
```
Newest **curse** CWG FPV, newest **curse** CC+CWG.
Result: **Stable**

**Comment by Foghrye4** [comment]
Thank you, that is known issue. Fixing in progress.

**Comment by Foghrye4** [comment]
Fixed.
